// <auto-generated />
using System;
using LearnHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnHub.Migrations
{
    [DbContext(typeof(LearnHubDbContext))]
    partial class LearnHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LearnHub.Models.Certificate", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("CertificateNumber").IsRequired().HasColumnType("TEXT");
                b.Property<int>("CourseId").HasColumnType("INTEGER");
                b.Property<DateTime>("IssuedAt").HasColumnType("TEXT");
                b.Property<int>("UserId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("CourseId");
                b.HasIndex("UserId");
                b.ToTable("Certificates");
            });

            modelBuilder.Entity("LearnHub.Models.ContactMessage", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Message").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<DateTime>("SentAt").HasColumnType("TEXT");
                b.Property<string>("Subject").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("ContactMessages");
            });

            modelBuilder.Entity("LearnHub.Models.Course", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("ImageUrl").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Instructor").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<decimal>("Price").HasColumnType("TEXT");
                b.Property<double>("Rating").HasColumnType("REAL");
                b.Property<int>("StudentCount").HasColumnType("INTEGER");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Courses");
            });

            modelBuilder.Entity("LearnHub.Models.Enrollment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("CourseId").HasColumnType("INTEGER");
                b.Property<DateTime>("EnrolledAt").HasColumnType("TEXT");
                b.Property<bool>("IsPaid").HasColumnType("INTEGER");
                b.Property<string>("PaymentMethod").IsRequired().HasColumnType("TEXT");
                b.Property<int>("UserId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("CourseId");
                b.HasIndex("UserId");
                b.ToTable("Enrollments");
            });

            modelBuilder.Entity("LearnHub.Models.QuizAttempt", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("AttemptedAt").HasColumnType("TEXT");
                b.Property<int>("CourseId").HasColumnType("INTEGER");
                b.Property<bool>("Passed").HasColumnType("INTEGER");
                b.Property<int>("Score").HasColumnType("INTEGER");
                b.Property<int>("TotalQuestions").HasColumnType("INTEGER");
                b.Property<int>("UserId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("CourseId");
                b.HasIndex("UserId");
                b.ToTable("QuizAttempts");
            });

            modelBuilder.Entity("LearnHub.Models.QuizQuestion", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("CourseId").HasColumnType("INTEGER");
                b.Property<string>("CorrectAnswer").IsRequired().HasColumnType("TEXT");
                b.Property<int>("OrderIndex").HasColumnType("INTEGER");
                b.Property<string>("OptionA").IsRequired().HasColumnType("TEXT");
                b.Property<string>("OptionB").IsRequired().HasColumnType("TEXT");
                b.Property<string>("OptionC").IsRequired().HasColumnType("TEXT");
                b.Property<string>("OptionD").IsRequired().HasColumnType("TEXT");
                b.Property<string>("QuestionText").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("CourseId");
                b.ToTable("QuizQuestions");
            });

            modelBuilder.Entity("LearnHub.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<bool>("IsAdmin").HasColumnType("INTEGER");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
